### ISSUE TITLE
got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by sfahad1414** [emmett-framework/granian#114]
--Code ---
from fastapi import FastAPI
from rasa.core.agent import Agent
from pydantic import BaseModel
import uuid6
app = FastAPI()

class Input(BaseModel):
    sender_id: str
    text: str

agent = Agent.load("./models/20230818-091151.tar.gz")

@app.get("/")
async def h():
    return "Hello, world!"

@app.post("/chat")
async def chat():
    return await agent.handle_text("Hi", sender_id=uuid6.uuid7().hex)

async def main(scope, receive, send):
    await app.__call__(scope=scope, receive=receive, send=send)

---Log Trace---
granian --workers 1 --threads 10 test:main --interface asgi
[INFO] Starting granian
[INFO] Listening at: 127.0.0.1:8000
[INFO] Spawning worker-1 with pid: 35682
/data/miniconda3/envs/RasaNew/lib/python3.8/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2023-08-19 13:48:41.108714: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-19 13:48:41.153718: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-19 13:48:41.154057: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-19 13:48:41.959277: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/data/miniconda3/envs/RasaNew/lib/python3.8/site-packages/rasa/core/tracker_store.py:1042: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
[INFO] Loading model ./models/20230819-132002-calm-tenant.tar.gz...
/data/miniconda3/envs/RasaNew/lib/python3.8/site-packages/rasa/shared/core/slot_mappings.py:224: UserWarning: Slot auto-fill has been removed in 3.0 and replaced with a new explicit mechanism to set slots. Please refer to https://rasa.com/docs/rasa/domain#slots to learn more.
  rasa.shared.utils.io.raise_warning(
2023-08-19 13:48:43.872344: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
         [[{{node Placeholder/_0}}]]
/data/miniconda3/envs/RasaNew/lib/python3.8/site-packages/rasa/utils/train_utils.py:525: UserWarning: constrain_similarities is set to `False`. It is recommended to set it to `True` when using cross-entropy loss.
  rasa.shared.utils.io.raise_warning(
/data/miniconda3/envs/RasaNew/lib/python3.8/site-packages/rasa/shared/utils/io.py:99: UserWarning: Training data file /tmp/tmp49enik8c/domain_provider/domain.yml has a lower format version than your Rasa Open Source installation: 2.0 < 3.1. Rasa Open Source will read the file as a version 3.1 file. Please update your version key to 3.1. See https://rasa.com/docs/rasa/training-data-format.
/data/miniconda3/envs/RasaNew/lib/python3.8/site-packages/rasa/shared/core/slot_mappings.py:224: UserWarning: Slot auto-fill has been removed in 3.0 and replaced with a new explicit mechanism to set slots. Please refer to https://rasa.com/docs/rasa/domain#slots to learn more.
  rasa.shared.utils.io.raise_warning(
2023-08-19 13:48:53.736045: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
         [[{{node Placeholder/_0}}]]
Process granian-worker:
Traceback (most recent call last):
  File "/data/miniconda3/envs/RasaNew/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/miniconda3/envs/RasaNew/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/miniconda3/envs/RasaNew/lib/python3.8/site-packages/granian/server.py", line 121, in _spawn_asgi_worker
    loop.run_until_complete(lifespan_handler.startup())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/data/miniconda3/envs/RasaNew/lib/python3.8/site-packages/granian/asgi.py", line 47, in startup
    await self.event_startup.wait()
  File "/data/miniconda3/envs/RasaNew/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-1' coro=<LifespanProtocol.startup() running at /data/miniconda3/envs/RasaNew/lib/python3.8/site-packages/granian/asgi.py:47> cb=[run_until_complete.<locals>.done_cb()]> got Future <Future pending> attached to a different loop

**Comment by gi0baro** [comment]
If `Agent` class performs async operations and stores reference to the loop, you should move it in the `lifespan` protocol. See https://fastapi.tiangolo.com/advanced/events
