### ISSUE TITLE
sniffio._impl.AsyncLibraryNotFoundError: unknown async library, or not in async context

### ISSUE THREAD

**Issue by sfahad1414** [emmett-framework/granian#127]
[ERROR] Exception in callback <built-in method _loop_task of builtins.CallbackRunnerHTTP object at 0x7f715067de70>
--
handle: <Handle CallbackRunnerHTTP._loop_task>
Traceback (most recent call last):
File "uvloop/cbhandles.pyx", line 61, in uvloop.loop.Handle._run
File "/app/kairon/chat/server.py", line 258, in main
await app.__call__(scope=scope, receive=receive, send=send)
File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
await super().__call__(scope, receive, send)
File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/local/lib/python3.10/site-packages/elasticapm/instrumentation/packages/asyncio/starlette.py", line 48, in call
return await wrapped(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
raise exc
File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
await self.app(scope, receive, _send)
File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 29, in __call__
response_sent = anyio.Event()
File "/usr/local/lib/python3.10/site-packages/anyio/_core/_synchronization.py", line 79, in __new__
return get_asynclib().Event()
File "/usr/local/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 147, in get_asynclib
asynclib_name = sniffio.current_async_library()
File "/usr/local/lib/python3.10/site-packages/sniffio/_impl.py", line 93, in current_async_library
raise AsyncLibraryNotFoundError(
sniffio._impl.AsyncLibraryNotFoundError: unknown async library, or not in async context

**Comment by gi0baro** [comment]
Looks like you launched Granian with `--opt`. [As described in the readme](https://github.com/emmett-framework/granian#event-loop-optimizations), some implementations are not compatible with the optimizations, so just keep those optimizations off (as per default).
