### ISSUE TITLE
Quart on Windows 10 raises RuntimeError: Already mutably borrowed

### ISSUE THREAD

**Issue by wdscxsj** [emmett-framework/granian#128]
`app.py`:

```py
from quart import Quart

app = Quart(__name__)

@app.get('/')
async def hello():
    return 'Hello'
```

On Windows 10, the following command raises RuntimeError: Already mutably borrowed:

```
granian --interface asgi app
```

It works well on Linux.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/emmett-framework/granian/issues/128">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/emmett-framework/granian/issues/128/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/emmett-framework/granian/issues/128/pledge.svg">
</picture>
</a>

**Comment by gi0baro** [comment]
@wdscxsj do you have a stack trace for this? Does it happen during launch on the requests?

**Comment by wdscxsj** [comment]
@gi0baro It only happens on requests. Please see the following stack trace generated on my machine (Windows 10 64-bit with Python 3.11.5):

```
C:\Tmp\tmp>granian --interface asgi app
[INFO] Starting granian
[INFO] Listening at: 127.0.0.1:8000
[INFO] Spawning worker-1 with pid: 10864
[INFO] Started worker-1
[INFO] Started worker-1 runtime-1
[WARNING] Application callable raised an exception
[ERROR] Task exception was never retrieved
future: <Task finished name='Task-4' coro=<future_watcher_wrapper.<locals>.future_watcher() done, defined at C:\Tools\Python3\Lib\site-packages\granian\_futures.py:2> exception=RuntimeError('Already mutably borrowed')>
Traceback (most recent call last):
  File "C:\Tools\Python3\Lib\site-packages\granian\_futures.py", line 4, in future_watcher
    await inner(watcher.scope, watcher.proto)
  File "C:\Tools\Python3\Lib\site-packages\quart\app.py", line 1620, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Tools\Python3\Lib\site-packages\quart\app.py", line 1646, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Tools\Python3\Lib\site-packages\quart\asgi.py", line 52, in __call__
    raise_task_exceptions(done)
  File "C:\Tools\Python3\Lib\site-packages\quart\utils.py", line 187, in raise_task_exceptions
    raise task.exception()
  File "C:\Tools\Python3\Lib\site-packages\quart\asgi.py", line 107, in handle_request
    await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
  File "C:\Tools\Python3\Lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Tools\Python3\Lib\site-packages\quart\asgi.py", line 136, in _send_response
    await send(
RuntimeError: Already mutably borrowed
[WARNING] Application callable raised an exception
[ERROR] Task exception was never retrieved
future: <Task finished name='Task-9' coro=<future_watcher_wrapper.<locals>.future_watcher() done, defined at C:\Tools\Python3\Lib\site-packages\granian\_futures.py:2> exception=RuntimeError('Already mutably borrowed')>
Traceback (most recent call last):
  File "C:\Tools\Python3\Lib\site-packages\granian\_futures.py", line 4, in future_watcher
    await inner(watcher.scope, watcher.proto)
  File "C:\Tools\Python3\Lib\site-packages\quart\app.py", line 1620, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Tools\Python3\Lib\site-packages\quart\app.py", line 1646, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Tools\Python3\Lib\site-packages\quart\asgi.py", line 52, in __call__
    raise_task_exceptions(done)
  File "C:\Tools\Python3\Lib\site-packages\quart\utils.py", line 187, in raise_task_exceptions
    raise task.exception()
  File "C:\Tools\Python3\Lib\site-packages\quart\asgi.py", line 107, in handle_request
    await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
  File "C:\Tools\Python3\Lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Tools\Python3\Lib\site-packages\quart\asgi.py", line 126, in _send_response
    await send(
RuntimeError: Already mutably borrowed
```

**Comment by gi0baro** [comment]
This might be fixed by https://github.com/emmett-framework/granian/commit/875f89f2d4169f12481ff47c15c45441af67d75d

**Comment by wdscxsj** [comment]
@gi0baro The fixed works on my computer. Thank you very much!
