### ISSUE TITLE
ValueError: Django can only handle ASGI/HTTP connections, not lifespan.

### ISSUE THREAD

**Issue by Zerotask** [emmett-framework/granian#153]
I'm using Django with ASGI granian:
> granian --threads 8 --host 0.0.0.0 --port 8000 --interface asgi base.asgi:application

and I noticed the following in my Debian based docker container:
> [WARNING] Exception in lifespan protocol
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/granian/asgi.py", line 24, in handle
    await self.callable(
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/django/asgi.py", line 80, in sentry_patched_asgi_handler
    return await middleware(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/asgi.py", line 146, in _run_asgi3
    return await self._run_app(scope, receive, send, asgi_version=3)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/asgi.py", line 161, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/asgi.py", line 157, in _run_app
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 155, in __call__
    raise ValueError(
ValueError: Django can only handle ASGI/HTTP connections, not lifespan.
[INFO] Started worker-1

I don't know if this issue is related to granian or the Sentry SDK.

**Comment by gi0baro** [comment]
That's just a warning, your app should be served correctly.
Granian expects ASGI/3 interfaces, and lifespan is a part of the protocol. If the application doesn't support lifespan then Granian will just trigger that warning and keep going on.

We might consider to add an option to disable lifespan, but I'm gonna close this as it doesn't really cause any malfunctioning.

**Comment by Zerotask** [comment]
It would be great to have an option to disable lifespan. We're using Sentry and this warning is the reason our quota depletes after a few days making Sentry useless for us at the moment.

**Comment by gi0baro** [comment]
@Zerotask with 1.2.0 you can use `--interface asginl`

**Comment by Zerotask** [comment]
Thank you :) Already updated
