### ISSUE TITLE
 granian.Granian method is failing

### ISSUE THREAD

**Issue by sreenivasulureddysura** [emmett-framework/granian#357]
I can use it in uvicorn below approach

```
if __name__ == "__main__":
    uvicorn.run("main:app", host='0.0.0.0' port=8080, log_level="info", reload=True)

```
How to use the granian.Granian with different options? 

```
 import granian
>>> granian.Granian(target='asgi', address='0.0.0.0', port=8000, workers=1).serve()
[INFO] Starting granian (main PID: 20992)
[INFO] Listening at: http://0.0.0.0:8000
[INFO] Spawning worker-1 with pid: 23396
  File "C:\Lib\site-packages\granian\_internal.py", line 40, in load_module
    __import__(module_name)
ModuleNotFoundError: No module named 'asgi'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
  File "C:\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Lib\site-packages\granian\server.py", line 304, in _spawn_rsgi_worker
             ^^^^^^^^^^^^^^^^^
  File "C:\Lib\site-packages\granian\_internal.py", line 58, in load_target
             ^^^^^^^^^^^^^^^^^
    raise RuntimeError(f"Could not import '{module_name}'.")
RuntimeError: Could not import 'asgi'.
[ERROR] Unexpected exit from worker-1
[INFO] Shutting down granian
```

**Comment by sreenivasulureddysura** [comment]
@gi0baro Can you help me on this issue?
