### ISSUE TITLE
Error when trying to use CLI - TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by antonpetrov145** [emmett-framework/granian#445]
When I try to execute any CLI command even `granian --help` I get this error:
```
Traceback (most recent call last):
  File ".../venv/bin/granian", line 5, in <module>
    from granian import cli
  File ".../venv/lib/python3.9/site-packages/granian/cli.py", line 247, in <module>
    def cli(
  File ".../venv/lib/python3.9/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
TypeError: 'NoneType' object is not callable
```
Python version 3.9.17
Granian version 1.6.4
Pyenv is used to make the virtual environment

**Comment by gi0baro** [comment]
@antonpetrov145 I can't reproduce your issue.
It also seems more related to `click` package than Granian itself. You should probably open an issue with them.
