### ISSUE TITLE
cannot pickle _io.TextiOWrapper

### ISSUE THREAD

**Issue by albertoreis86** [emmett-framework/granian#79]
getting this error when trying to run the application

2023-05-25 15:16:07,111] INFO root Starting granian
[2023-05-25 15:16:07,112] INFO root Listening at: 0.0.0.0:8080
Traceback (most recent call last):
  File "/Users/myuser/project_folder/project_subfolder/app/server.py", line 48, in <module>
    run_application()
  File "/Users/myuser/project_folder/project_subfolder/app/server.py", line 28, in run_application
    granian.serve()
  File "/Users/myuser/Library/Caches/pypoetry/virtualenvs/sigrhe-bmt3Z-Ej-py3.11/lib/python3.11/site-packages/granian/server.py", line 368, in serve
    serve_method(spawn_target, target_loader)
  File "/Users/myuser/Library/Caches/pypoetry/virtualenvs/sigrhe-bmt3Z-Ej-py3.11/lib/python3.11/site-packages/granian/server.py", line 335, in _serve_with_reloader
    sock = self.startup(spawn_target, target_loader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/Library/Caches/pypoetry/virtualenvs/sigrhe-bmt3Z-Ej-py3.11/lib/python3.11/site-packages/granian/server.py", line 321, in startup
    self._spawn_workers(sock, spawn_target, target_loader)
  File "/Users/myuser/Library/Caches/pypoetry/virtualenvs/sigrhe-bmt3Z-Ej-py3.11/lib/python3.11/site-packages/granian/server.py", line 300, in _spawn_workers
    proc.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object

**Comment by albertoreis86** [comment]
not really actually,
this is how I instantiate:

granian = Granian(target=f'{settings.APPLICATION_PATH}',
                      address=settings.SERVER_HOST,
                      port=settings.PORT,
                      interface=constants.Interfaces.ASGI,
                      workers=settings.WORKERS_NUMBER,
                      log_level=log.LogLevels.debug if settings.DEBUG else log.LogLevels.info,
                      ssl_cert=cert_file_path if cert_file_path.exists() else None,
                      ssl_key=cert_keyfile_path if cert_keyfile_path.exists() else None,
                      reload=settings.RELOAD_SERVER,
                      log_dictconfig=logging_config)
    granian.serve()

**Comment by albertoreis86** [comment]
Yes we use to run this with hypercorn and was going ok.,
indeed it is macOS, the other members of the team can run it normally using linux.
the default value for workers number is 1.

**Comment by gi0baro** [comment]
Ok so probably if you call:

```python
import multiprocessing
multiprocessing.set_start_method('fork')
```

you should be able to run it in the same way it works on Linux.

What it still sound strange to me, is why you have an `_io.TextIOWrapper` instance defined somewhere before starting `granian`. It sounds like you opened a file or a stream and never closed it, or never parsed the context of that stream. Probably just a `str(variable)` would make the thing pickable.

**Comment by albertoreis86** [comment]
Thanks @gi0baro it worked explicitly setting the start method to fork.
I will dig into the _io.TextIOWrapper I will dig into it.
Thanks
